### PR TITLE
Fix bug with 'visibilitychange' event and paused instances (fixes: #560)

### LINKED ISSUE #560: the removed animation played when page state changed (document visibilitychange event)
Describe the bug: 
  I remove an animation, but it played when i trigger the document visibilitychange event. 
  I found that It doesn't remove the animation when i removed. And when it run into visibilitychange event, it played all of pause animation. 

To Reproduce:
1. remove an animation
2. i slide my desktop on my mac, i guess switch tab also can trigger the bug. Anyway, to trigger the visibilitychange event.

Expected behavior:
1. my removed animation can not replay

Desktop:
browser chrome v73.0.3683.75

### PR DESCRIPTION
**Pull request by fljot**
Few fixes and improvements, please review by individual commits.

Main point was to fix `"visibilitychange"` event handling (d6f096be4ca3ee0adfbe25e39b2b47ec196f654b) – looks similar to closed #560, but still wasn't working properly in `3.2.0`.

Bug demo: https://codepen.io/fljot/pen/oNbEdBj

CC: @juliangarnier @chrisbrown-io @elvira1112

...but during fixing that I also noticed a couple other issues and things to improve around engine ticks. Fixes and improvements are commited separately, with respective comments.

Finally there's also suggestion to be able to configure `"visibilitychange"` event handling strategy (1ecb30147be3d3fbf0ee510c1d4aa5dbfa8a0d92) – whether to suspend rAF ticks or not (as suggested in #335 and recent #711)

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -834,50 +834,57 @@ function createNewInstance(params) {
...
+
+  function handleVisibilityChange() {
+    if (!anime.suspendWhenDocumentHidden) return;
+
+    if (isDocumentHidden()) {
+      // suspend ticks
       raf = cancelAnimationFrame(raf);
+    } else { // is back to active tab
+      // first adjust animations to consider the time that ticks were suspended
+      activeInstances.forEach(
```
Comment (Ridvanovskyy) [inline src/index.js:873]: Question to @juliangarnier 
[ _**animations are now paused when tab of window is not active**_](https://github.com/juliangarnier/anime/releases/tag/v3.0.0)
What's the point of pause animation when the tab is inactive? As i see, Anime.js works through **RAF** and nowadays everywhere it automatically pauses itself. As far as I understood, this was done due to the support of old browsers such as Сhrome 24+ in 1 and 2 versions of Anime.js. We can see in these versions that anime.js added browser vendor prefixes styles. 
As I understand, version 3 does not support these old browsers, because browser vendor prefixes are not set in the styles and they are not set in the _**visibilitychange**_ event.
Also i cheched GSAP, PIXI and they are handle this with native RAF pause. 
I found that only [Phaser](https://github.com/photonstorm/phaser/blob/b46776a2c0a623bf2078b533cf29d02d24663fc0/src/core/VisibilityHandler.js) handling this(mb for very old browsers).
I propose to remove the pausing animations in an inactive tab in version 3, it is simply not needed since version 3 is not aimed at such old browsers where it does not automatically pause. What do you think @juliangarnier @fljot

File: src/index.js [hunk 2]
```diff
@@ -1244,6 +1254,8 @@ function timeline(params = {}) {
 
 anime.version = '3.2.0';
 anime.speed = 1;
+// TODO:#review: naming, documentation
+anime.suspendWhenDocumentHidden = true;
```
Comment (kn0wn) [inline src/index.js:1258]: I think due to this being a feature point of the v3 release and so that there is consistency with the minor updates, the default should be set to `false`. A major could introduce this as default behaviour.

Comment (fljot) [reply src/index.js:1258]: But `true` behavior is exactly the current "master" (3.2.0) one, where stuff gets paused – so I **did** care about semver and preserving behavior)

... though, again, overall this behavior nowdays looks already unnecessary according to @Ridvanovskyy in https://github.com/juliangarnier/anime/pull/701#discussion_r459670684

File: src/index.js (hunk 1 above)
Comment (juliangarnier) [reply src/index.js:873]: The only reason to force the RAF to pause is to restore the animations state where they were just before switching tab.
Otherwise, the animations currentTime will skip to where it should be if the tab did't change.

**Comment by juliangarnier** [comment]
Great PR, I'll merge this into 3.2.1 for now, and will create the doc for it soon.
Not sure about "suspendWhenDocumentHidden" name, maybe something less verbose, like "autoPause" what do you think? Otherwise great job!

**Comment by fljot** [comment]
@juliangarnier thnx!

>Not sure about "suspendWhenDocumentHidden" name, maybe something less verbose, like "autoPause" what do you think? Otherwise great job!

I often advocate for verbose and explicit naming, especially when it's a top-level configuration with questionable (as in "unclear") purpose 😎 
Mr @Ridvanovskyy 's reasoning above makes sense to me, I also don't get what's the point of this behavior nowdays...

**Comment by juliangarnier** [comment]
> Mr @Ridvanovskyy 's reasoning above makes sense to me, I also don't get what's the point of this behavior nowdays...

@fljot @Ridvanovskyy's reasoning makes sense, but it doesn't take into account that the current behaviour not only pauses the RAF, but also re-sync the animations where they where currently playing before switching tab.

I think having both options makes sense:
By default you don't miss anything from the animation when switching tabs, useful if you want the user to see specific data in a certain order.
But you can choose to let everything "run" normally in the background without any pause, like a video or an audio track that can continuously plays in the background.

Regarding the name, I can't find anything better for now, so will probably stick with "suspendWhenDocumentHidden".
